#!/bin/sh
set -e

APP="rusty-calendar-pi"

case "$1" in
remove|upgrade|deconfigure)
    systemctl stop "$APP.service" >/dev/null 2>&1 || true
    systemctl disable "$APP.service" >/dev/null 2>&1 || true
    ;;
esac
